version: '3'
services:
  web1:
    build: ./Transaction
    ports:
      - "8000:80"
  web2:
    build: ./Client
    ports:
      - "8001:80"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "ChangeIt"
      ACCEPT_EULA: "Y"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
